name: 'robodog'
services:
  robodog:
    build: .
    container_name: robodog-bot
    volumes:
      - ./data:/app/data
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - TIP_URL=${TIP_URL}
      - CHALLENGE_URL=${CHALLENGE_URL}
    restart: unless-stopped
